clear 
home_dir = '/overflow/tengfei/user/tengfei/projects/UKB_PSC_CommonAtlas/OtherModality/plot_and_QC/fMRI_coupling/PopulationAnalysis' 
code_dir = fullfile(home_dir,'code_nonmask'); 
mkdir(code_dir); 
delete(sprintf('%s/*',code_dir)); 
fid0=fopen(sprintf('%s/All.sh',code_dir),'w'); 
fprintf(fid0,'#!/bin/bash \n');
for iii=1:78 
batNames = sprintf('%s/bat%i.pbs',code_dir,iii);
fid = fopen(batNames,'w');
fprintf(fid,'#!/bin/bash \n');
fprintf(fid,'#SBATCH --ntasks=1 \n');
fprintf(fid,'#SBATCH --time=1:59:59 \n');
fprintf(fid,'#SBATCH --mem=32000 \n');
fprintf(fid,'#SBATCH --wrap=mytask \n');
fprintf(fid,'cd /overflow/tengfei/user/tengfei/projects/UKB_PSC_CommonAtlas/OtherModality/plot_and_QC/fMRI_coupling/PopulationAnalysis/ \n');
fprintf(fid,'module load r/4.4.0 \n');
fprintf(fid,'R CMD BATCH --no-save --no-restore %s/bat%i.r %s/bat%i.out\n',code_dir,iii,code_dir,iii); 
fclose(fid); 
fprintf(fid0,'sbatch bat%i.pbs\n',iii);
batNames = sprintf('%s/bat%i.r',code_dir,iii);
fid = fopen(batNames,'w');
fprintf(fid,'iii=53 \n');
fprintf(fid,'iii=%i \n',iii);
fprintf(fid,'library(pls) \n');
fprintf(fid,'library(data.table) \n');
fprintf(fid,'fileT=Sys.glob("G360_PC/ph12/PCs*.txt") \n');
fprintf(fid,'A=fread(fileT[iii],data.table=F) \n');
fprintf(fid,'A1=fread(gsub("/ph12/","/ph3/",fileT[iii]),data.table=F) \n');
fprintf(fid,'fileT0=gsub("_100.txt","",gsub("G360_PC/ph12/PCs_","",fileT)) \n');
fprintf(fid,'UNet=union(unlist(lapply(strsplit(fileT0,"_"),"[",1)),unlist(lapply(strsplit(fileT0,"_"),"[",2))) \n');
fprintf(fid,'Net0=strsplit(fileT0[iii],"_")[[1]] \n');
fprintf(fid,'A=rbind(A,A1) \n');
fprintf(fid,'rm(list=c("A1")) \n');
fprintf(fid,'outfile=gsub("_100.txt","",gsub("G360_PC/ph12/PCs_","",fileT[iii])) \n');
fprintf(fid,'outfold="G360_PC_CBSS_Line_nonmask_out/" \n');
fprintf(fid,'outfold1="G360_CBSS_Line_nonmask_out/" \n');
fprintf(fid,'system(paste0("mkdir ",outfold)) \n');
fprintf(fid,'system(paste0("mkdir ",outfold1)) \n');
fprintf(fid,'rownames(A)=A[,1];A=A[,-1] \n');
fprintf(fid,'pp=dim(A)[2] \n');
fprintf(fid,'for(ii in 1:dim(A)[2]) \n');
fprintf(fid,'{ \n');
fprintf(fid,'print(dim(A)[2]-ii) \n');
fprintf(fid,'med0=median(A[,ii],na.rm=T) \n');
fprintf(fid,'mad0=mad(A[,ii],na.rm=T) \n');
fprintf(fid,'A[which(abs(A[,ii]-med0)>5*mad0),ii]=NA \n');
fprintf(fid,'indtemp=which(is.na(A[,ii])) \n');
fprintf(fid,'if(length(indtemp)>0)A[indtemp,ii]=median(A[,ii],na.rm=T) \n');
fprintf(fid,'} \n');
fprintf(fid,'B_train=fread("../../../PCA_ELReg/FA_UKB_Phase12/Mean.txt",data.table=F) \n');
fprintf(fid,'rownames(B_train)=B_train[,1];B_train=B_train[,-1] \n');
fprintf(fid,'B_test=fread("../../../PCA_ELReg/FA_UKB_Phase3_proj/Mean.txt",data.table=F) \n');
fprintf(fid,'rownames(B_test)=B_test[,1];B_test=B_test[,-1] \n');
fprintf(fid,'atlas0=fread("../../../template/Fiber_atlas_100points_FullName_qc_LenCurv.csv",data.table=F) \n');
fprintf(fid,'ind00=which(!((atlas0$Net1%%in%%Net0)|(atlas0$Net2%%in%%Net0))) #############change this to non-coupling network \n');
fprintf(fid,'B_train=B_train[,ind00];B_test=B_test[,ind00]; \n');
fprintf(fid,'UID_train=intersect(rownames(A),rownames(B_train)) \n');
fprintf(fid,'UID_test=intersect(rownames(A),rownames(B_test)) \n');
fprintf(fid,'A_train=A[UID_train,];B_train=B_train[UID_train,] \n');
fprintf(fid,'A_test=A[UID_test,];B_test=B_test[UID_test,] \n');
fprintf(fid,'A_train <- scale(A_train, center = TRUE, scale = TRUE) \n');
fprintf(fid,'B_train <- scale(B_train, center = TRUE, scale = TRUE) \n');
fprintf(fid,'A_test  <- scale(A_test, center = attr(A_train, "scaled:center"), scale = attr(A_train, "scaled:scale")) \n');
fprintf(fid,'B_test  <- scale(B_test, center = attr(B_train, "scaled:center"), scale = attr(B_train, "scaled:scale")) \n');
fprintf(fid,'M <- rep(NA, pp);names(M)=colnames(A) \n');
fprintf(fid,'names(M) <- colnames(A) \n');
fprintf(fid,'ncomp0=4 \n');
fprintf(fid,'A_pred <- A_test;A_pred[T]=NA \n');
fprintf(fid,'for (ii in 1:pp) { \n');
fprintf(fid,'  print(pp-ii) \n');
fprintf(fid,'  pls_model <- plsr(A_train[,ii] ~ B_train, ncomp = ncomp0, validation = "none")  # choose ncomp by CV if needed \n');
fprintf(fid,'  A_pred[,ii] <- predict(pls_model, newdata = B_test, ncomp = ncomp0)[,1,1] \n');
fprintf(fid,'  M[ii] <- cor(A_pred[,ii], A_test[, ii]) \n');
fprintf(fid,'  print(M[ii]) \n');
fprintf(fid,'} \n');
fprintf(fid,'write.table(M,file=paste0(outfold,outfile,"_cor.txt"),quote=F) \n');
fprintf(fid,'A_pred1=t(t(A_pred)*attr(A_train,"scaled:scale")+attr(A_train,"scaled:center"));colnames(A_pred1)=colnames(A) \n');
fprintf(fid,'write.table(A_pred1,file=paste0(outfold,outfile,"_pred.txt"),quote=F) \n');
fprintf(fid,'pcnum=read.table(paste0("G360_PC/ph12/PC_",outfile,".txt"))[[1]] \n');
fprintf(fid,'ind00=which(pcnum>0.9);qqmax=100;if(length(ind00)>0)qqmax=ind00[1] \n');
fprintf(fid,'qq=1:qqmax \n');
fprintf(fid,'A_pred1=A_pred1[,qq] \n');
fprintf(fid,'Eigv=read.table(paste0("G360_PC/ph12/Eigv_",outfile,"_100.txt")) \n');
fprintf(fid,'sd1=read.table(paste0("G360_PC/ph12/sd_",outfile,".txt"))[[1]] \n');
fprintf(fid,'mu1=read.table(paste0("G360_PC/ph12/mu0_",outfile,".txt"))[[1]] \n');
fprintf(fid,'AT=fread(paste0("G360/",outfile,".txt.gz"),data.table=F) \n');
fprintf(fid,'rownames(AT)=AT[,1];AT=AT[,-1] \n');
fprintf(fid,'pp=dim(AT)[2] \n');
fprintf(fid,'for(ii in 1:dim(AT)[2]) \n');
fprintf(fid,'{ \n');
fprintf(fid,'med0=median(AT[,ii],na.rm=T) \n');
fprintf(fid,'mad0=mad(AT[,ii],na.rm=T) \n');
fprintf(fid,'AT[which(abs(AT[,ii]-med0)>5*mad0),ii]=NA \n');
fprintf(fid,'indtemp=which(is.na(AT[,ii])) \n');
fprintf(fid,'if(length(indtemp)>0)AT[indtemp,ii]=median(AT[,ii],na.rm=T) \n');
fprintf(fid,'} \n');
fprintf(fid,'A_test1=AT[rownames(A_test),] \n');
fprintf(fid,'A_train1=AT[rownames(A_train),] \n');
fprintf(fid,'A_pred1=as.matrix(A_pred1)%%*%%t(as.matrix(Eigv)[,qq])%%*%%diag(sd1^2) \n');
fprintf(fid,'A_pred1=t(t(A_pred1)+mu1) \n');
fprintf(fid,'cb_metrics <- function(A_pred1, A_test1, A_train1 = NULL) { \n');
fprintf(fid,'  A_pred1 <- as.matrix(A_pred1) #A_pred \n');
fprintf(fid,'  A_test1 <- as.matrix(A_test1) \n');
fprintf(fid,'  n <- nrow(A_test1) \n');
fprintf(fid,'  row_corr <- function(A, B) { \n');
fprintf(fid,'    A <- scale(A, center = TRUE, scale = FALSE) \n');
fprintf(fid,'    B <- scale(B, center = TRUE, scale = FALSE) \n');
fprintf(fid,'    num <- rowSums(A * B) \n');
fprintf(fid,'    den <- sqrt(rowSums(A^2) * rowSums(B^2)) \n');
fprintf(fid,'    num / den \n');
fprintf(fid,'  } \n');
fprintf(fid,'  mu_tr <- colMeans(A_train1) \n');
fprintf(fid,'  r_rows_demean <- row_corr(sweep(A_pred1, 2, mu_tr),sweep(A_test1, 2, mu_tr)) \n');
fprintf(fid,'  avgcorr_demean <- mean(r_rows_demean, na.rm = TRUE)#0.157 \n');
fprintf(fid,'  #3. avgrank \n');
fprintf(fid,'  Xn <- t(scale(t(A_test1))) \n');
fprintf(fid,'  Yn <- t(scale(t(A_pred1))) \n');
fprintf(fid,'  C <- Xn %%*%% t(Yn)/dim(Xn)[2]  # n×n correlation matrix \n');
fprintf(fid,'  mm=rep(NA,dim(Xn)[1]);for(ii in 1:dim(Xn)[1])mm[ii]= mean(C[ii,]<C[ii,ii]) \n');
fprintf(fid,'  avgrank <- mean(mm) #0.654 \n');
fprintf(fid,'  avgcorr <- mean(diag(C)) \n');
fprintf(fid,'  data.frame(avgcorr, avgcorr_demean, avgrank) \n');
fprintf(fid,'} \n');
fprintf(fid,'cb_metrics0=cb_metrics(A_pred1, A_test1, A_train1) \n');
fprintf(fid,'write.table(cb_metrics0,file=paste0(outfold1,outfile,"_metrics.txt"),quote=F) \n');
fprintf(fid,'write.table(A_pred1,file=paste0(outfold1,outfile,"_pred.txt"),quote=F) \n');
fclose(fid); 
end; 
fclose(fid0); 
clear all; 
