clear 
home_dir = '/overflow/tengfei/user/tengfei/projects/UKB_PSC_CommonAtlas/OtherModality/plot_and_QC/fMRI_coupling/PopulationAnalysis' 
code_dir = fullfile(home_dir,'code'); 
mkdir(code_dir); 
delete(sprintf('%s/*',code_dir)); 
fid0=fopen(sprintf('%s/All.sh',code_dir),'w'); 
fprintf(fid0,'#!/bin/bash \n');
for iii=1:61 
batNames = sprintf('%s/bat%i.pbs',code_dir,iii);
fid = fopen(batNames,'w');
fprintf(fid,'#!/bin/bash \n');
fprintf(fid,'#SBATCH --ntasks=1 \n');
fprintf(fid,'#SBATCH --time=23:59:59 \n');
fprintf(fid,'#SBATCH --mem=32000 \n');
fprintf(fid,'#SBATCH --wrap=mytask \n');
fprintf(fid,'cd /overflow/tengfei/user/tengfei/projects/UKB_PSC_CommonAtlas/OtherModality/plot_and_QC/fMRI_coupling/PopulationAnalysis/ \n');
fprintf(fid,'module load r/4.4.0 \n');
fprintf(fid,'R CMD BATCH --no-save --no-restore %s/bat%i.r %s/bat%i.out\n',code_dir,iii,code_dir,iii); 
fclose(fid); 
fprintf(fid0,'sbatch bat%i.pbs\n',iii);
batNames = sprintf('%s/bat%i.r',code_dir,iii);
fid = fopen(batNames,'w');
fprintf(fid,'iii=2 #1:61 \n');
fprintf(fid,'iii=%i \n',iii);
fprintf(fid,'library(data.table) \n');
fprintf(fid,'subT=Sys.glob(paste0("G360_out/*_pred.txt")) \n');
fprintf(fid,'patT=gsub("G360_out/","",gsub("_pred.txt","",subT)) \n');
fprintf(fid,'L=length(patT) \n');
fprintf(fid,'temp1=fread(subT[1],data.table=F) \n');
fprintf(fid,'rownames(temp1)=temp1[,1];temp1=temp1[,-1] \n');
fprintf(fid,'INDD=((iii-1)*300+1):min(iii*300,dim(temp1)[1]) \n');
fprintf(fid,'L0=length(INDD) \n');
fprintf(fid,'M1=matrix(NA,L0,64620) \n');
fprintf(fid,'rownames(M1)=rownames(temp1)[INDD];colnames(M1)=1:64620 \n');
fprintf(fid,'start0=1 \n');
fprintf(fid,'for(ii in 1:L) \n');
fprintf(fid,'{ \n');
fprintf(fid,'	print(L-ii) \n');
fprintf(fid,'	temp=fread(paste0("G360/",patT[ii],".txt.gz"),data.table=F) \n');
fprintf(fid,'	rownames(temp)=temp[,1];temp=temp[rownames(temp1)[INDD],-1] \n');
fprintf(fid,'	ptemp=dim(temp)[2] \n');
fprintf(fid,'	for(ii in 1:dim(temp)[2]){ \n');
fprintf(fid,'	med0=median(temp[,ii],na.rm=T) \n');
fprintf(fid,'	mad0=mad(temp[,ii],na.rm=T) \n');
fprintf(fid,'	temp[which(abs(temp[,ii]-med0)>5*mad0),ii]=NA \n');
fprintf(fid,'	indtemp=which(is.na(temp[,ii])) \n');
fprintf(fid,'	if(length(indtemp)>0){#print(length(indtemp)); \n');
fprintf(fid,'	temp[indtemp,ii]=median(temp[,ii],na.rm=T)}} \n');
fprintf(fid,'	M1[rownames(temp),start0:(start0+ptemp-1)]=as.matrix(temp) \n');
fprintf(fid,'	colnames(M1)[start0:(start0+ptemp-1)]=paste0(patT[ii],"_",colnames(temp)) \n');
fprintf(fid,'	start0=start0+ptemp \n');
fprintf(fid,'	print(64620-start0) \n');
fprintf(fid,'} \n');
fprintf(fid,'M=matrix(NA,dim(temp1)[1],64620) \n');
fprintf(fid,'rownames(M)=rownames(temp1);colnames(M)=1:64620 \n');
fprintf(fid,'start0=1 \n');
fprintf(fid,'for(ii in 1:L) \n');
fprintf(fid,'{ \n');
fprintf(fid,'	print(L-ii) \n');
fprintf(fid,'	temp=fread(subT[ii],data.table=F) \n');
fprintf(fid,'	rownames(temp)=temp[,1];temp=temp[,-1] \n');
fprintf(fid,'	ptemp=dim(temp)[2] \n');
fprintf(fid,'	M[rownames(temp),start0:(start0+ptemp-1)]=as.matrix(temp) \n');
fprintf(fid,'	colnames(M)[start0:(start0+ptemp-1)]=paste0(patT[ii],"_",colnames(temp)) \n');
fprintf(fid,'	start0=start0+ptemp \n');
fprintf(fid,'	print(64620-start0) \n');
fprintf(fid,'} \n');
fprintf(fid,' \n');
fprintf(fid,'for(ii in 1:dim(M)[1]){if(ii%%%%1000==0)print(dim(M)[1]-ii);M[ii,]=scale(M[ii,]);} \n');
fprintf(fid,'for(ii in 1:dim(M1)[1]){if(ii%%%%1000==0)print(dim(M1)[1]-ii);M1[ii,]=scale(M1[ii,]);} \n');
fprintf(fid,'M1=t(M1) \n');
fprintf(fid,'C=M[,1:1000]%%*%%M1[1:1000,] \n');
fprintf(fid,'NN=ceiling(dim(M)[2]/1000) \n');
fprintf(fid,'for(ii in 2:NN) \n');
fprintf(fid,'{ \n');
fprintf(fid,'print(dim(M)[2]-ii*1000) \n');
fprintf(fid,'ind000=((ii-1)*1000+1):min(ii*1000,dim(M)[2]) \n');
fprintf(fid,'C=C+M[,ind000]%%*%%M1[ind000,] \n');
fprintf(fid,'} \n');
fprintf(fid,'rownames(C)=rownames(M) \n');
fprintf(fid,'colnames(C)=colnames(M1) \n');
fprintf(fid,'write.table(C,file=paste0("G360_GlobalEval_out/",iii,".txt"),quote=F) \n');
fclose(fid); 
end; 
fclose(fid0); 
clear all; 
