clear 
home_dir = '/overflow/tengfei/user/tengfei/projects/UKB_PSC_CommonAtlas/OtherModality/';
Mat='step2_FA_UKB_Phase12_Lambda'; Mat1='step2_FA_UKB_Phase12'; 
code_dir = sprintf('%s/code_%s',home_dir,Mat);
mkdir(code_dir); 
mkdir(sprintf('%s/%s',home_dir,Mat));
delete(sprintf('%s/*',code_dir)); 
fid0=fopen(sprintf('%s/All.sh',code_dir),'w'); 
fprintf(fid0,'#!/bin/bash \n');
nn=6090;
K=609;
lambdaT=exp(linspace(log(0.01),0,10));
for iii=1:K
if exist(sprintf('%s/%s/%i_Aligned.mat',home_dir,Mat,iii))
continue;
end
batNames = sprintf('%s/bat%i.pbs',code_dir,iii);
fid = fopen(batNames,'w');
fprintf(fid,'#!/bin/bash \n');
fprintf(fid,'#SBATCH --ntasks=1 \n');
fprintf(fid,'#SBATCH --time=23:59:59 \n'); % 1:00 for phase12;0.5hour for HCP
fprintf(fid,'#SBATCH --mem=24000 \n'); %12 for retest;18 for phase4; dogwood can be large%%%%%%%%%%%%%%%%%%%%%%%
fprintf(fid,'#SBATCH --wrap=mytask \n');
fprintf(fid,'cd %s \n',code_dir);
fprintf(fid,'module load matlab/2019a \n');
fprintf(fid,'matlab -nodesktop -nosplash -nodisplay -r ''bat%i'' -logfile bat%i.out \n',iii,iii); 
fclose(fid); 
fprintf(fid0,'sbatch bat%i.pbs\n',iii);
batNames = sprintf('%s/bat%i.m',code_dir,iii);
fid = fopen(batNames,'w');
fprintf(fid,'clear all; \n');
fprintf(fid,'close all; \n');
fprintf(fid,'addpath(genpath(''../elastic'')) \n');
fprintf(fid,'Mat = ''%s''; \n',Mat);
fprintf(fid,'Mat1 = ''%s''; \n',Mat1);
fprintf(fid,'iii=1;%%1:117 \n');
fprintf(fid,'iii=%i \n',iii);
fprintf(fid,'lambdaT=exp(linspace(log(0.01),0,10)); lambdaL=length(lambdaT); \n');
fprintf(fid,'FiberL=readtable(''../plot_and_QC/atlas_100clust_100points_length.csv'');\n');
fprintf(fid,'N=10; \n');
fprintf(fid,'VoxelT=((iii-1)*N+1):min(iii*N,6090); \n');
fprintf(fid,'FiberL=FiberL{VoxelT,6}''; \n');
fprintf(fid,'N1=609;iii1=ceil(VoxelT(1)/N1);iii2=VoxelT(1)-(iii1-1)*N1; \n');
fprintf(fid,'fT=h5read(sprintf(''../%%s/%%i.h5'',Mat1,iii1),[''/'' ''M'']);\n');
fprintf(fid,'iii3=min(iii2+N-1,size(fT,2));fT=fT(:,iii2:iii3,:);\n');
fprintf(fid,'fT=permute(fT,[1,3,2]);\n');
fprintf(fid,'f_aligned = zeros([size(fT,2),size(fT,1),N,lambdaL])/0; \n');
fprintf(fid,'fmeanT=dlmread(sprintf(''../atlas/%%i_Mean.txt'',iii)); \n');
fprintf(fid,'L21=f_aligned; \n');
fprintf(fid,'TT=size(fT,2); \n');
fprintf(fid,'for jjj=1:length(VoxelT)  \n');
fprintf(fid,'	disp(length(VoxelT)-jjj)  \n');
fprintf(fid,'	lambda0=lambdaT*FiberL(jjj); \n');
fprintf(fid,'	f=fT(:,:,jjj)'';  \n');
fprintf(fid,'	M1=size(f,1);N11=size(f,2); \n'); %%
fprintf(fid,'	t=(1:TT)/TT;  \n');
fprintf(fid,'	fmean1=fmeanT(:,jjj);  \n');
fprintf(fid,'	a = size(t,1);  \n');
fprintf(fid,'	if (a ~=1)  \n');
fprintf(fid,'		t = t'';  \n');
fprintf(fid,'	end  \n');
fprintf(fid,'	binsize = mean(diff(t));  \n');
fprintf(fid,'	f0 = [fmean1,f];  \n');
fprintf(fid,'	[~,fy] = gradient(f0,binsize,binsize);  \n');
fprintf(fid,'	q = fy./sqrt(abs(fy)+eps);  \n');
fprintf(fid,'	q1 = q(:,1)'';  \n');
fprintf(fid,'	f_1 = f0(:,1);  \n');
fprintf(fid,'	for ii=2:size(f0,2)  \n');
fprintf(fid,'	    if mod(ii,100)==0  \n');
fprintf(fid,'	    disp(size(f0,2)-ii)  \n');
fprintf(fid,'	    end  \n');
fprintf(fid,'		q2 = q(:,ii)'';  \n');
fprintf(fid,'		f_2 = f0(:,ii);  \n');
fprintf(fid,'		for kkk=1:lambdaL	  \n');
fprintf(fid,'		   [G,T] = DynamicProgrammingQ2_1(q1/norm(q1),t,q2/norm(q2),t,t,t,lambda0(kkk));    \n');
fprintf(fid,'		   gam0 = interp1(T,G,t);    \n');
fprintf(fid,'		   gam_f = (gam0-gam0(1))/(gam0(end)-gam0(1));    \n');
fprintf(fid,'		   f_aligned(:,ii-1,jjj,kkk) = interp1(t, f_2, (t(end)-t(1)).*gam_f + t(1), ''v5cubic'')'';   \n'); 
fprintf(fid,'		   L21(:,ii-1,jjj,kkk)=gam_f;    \n');
fprintf(fid,'		end     \n');
fprintf(fid,'	end	  \n');
fprintf(fid,'end  \n');
fprintf(fid,'save(sprintf(''../%%s/%%i_%%s.mat'',Mat,iii,''Aligned''),''f_aligned'');  \n');
fprintf(fid,'save(sprintf(''../%%s/%%i_%%s.mat'',Mat,iii,''TimeShift''),''L21'');  \n');
fprintf(fid,'clear;exit;return;  \n');
fclose(fid); 
end; 
fclose(fid0); 
clear all; 
